using CVScreener.Core.Interfaces;
using CVScreener.Core.Models;
using CVScreener.Infrastructure.Services;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace CVScreener.Tests;

/// <summary>
/// Integration-style tests for OnnxInferenceService.
/// These tests load the REAL tfidf.onnx file from the ml/models/ directory.
///
/// Requirements:
///   - ml/models/tfidf.onnx must exist (generated by ml/train_tfidf.py).
///   - The model must have input name "input" and output shape [None, 5000].
///
/// ONNX model path: resolved relative to the test binary output directory.
///   Binary lives at: backend/tests/CVScreener.Tests/bin/Debug/net8.0/
///   Model lives at:  ml/models/tfidf.onnx
///   Relative path:   ../../../../ml/models/tfidf.onnx
/// </summary>
public class OnnxInferenceServiceTests
{
    private readonly IOnnxInferenceService _sut;

    // ── Vocabulary size produced by train_tfidf.py (max_features=5000) ─────────
    private const int ExpectedVectorLength = 5000;

    // ── Thresholds for similarity assertions ────────────────────────────────
    // TF-IDF is a term-frequency model, NOT a semantic embedding model (DEC-002).
    // It scores vocabulary overlap — not conceptual similarity between synonyms.
    // Two same-domain texts with partial vocabulary overlap realistically score 0.3–0.6.
    // A threshold of 0.35 is still meaningful (well above the zero baseline)
    // and appropriate for TF-IDF. Do NOT use 0.7+ thresholds (that's BERT territory).
    private const double SimilarThreshold   = 0.35;
    private const double UnrelatedThreshold = 0.20;

    public OnnxInferenceServiceTests()
    {
        // Resolve the ONNX model path relative to the test binary output directory.
        // Binary output: backend/tests/CVScreener.Tests/bin/Debug/net8.0/
        // Levels to root: net8.0 → Debug → bin → CVScreener.Tests → tests → backend → workspace root
        // Model file:    ml/models/tfidf.onnx  (6 levels up, then into ml/models/)
        var binaryDir  = AppContext.BaseDirectory;
        var modelPath  = Path.GetFullPath(
            Path.Combine(binaryDir, "../../../../../../ml/models/tfidf.onnx"));

        if (!File.Exists(modelPath))
            throw new FileNotFoundException(
                $"tfidf.onnx not found at '{modelPath}'. " +
                "Run ml/train_tfidf.py to generate the model file before running these tests.",
                modelPath);

        var options = Options.Create(new MlOptions { ModelPath = modelPath });
        _sut = new OnnxInferenceService(options, NullLogger<OnnxInferenceService>.Instance);
    }

    // ── Vectorize() ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Empty string input should return a zero vector of the correct length,
    /// not throw or return null.
    /// </summary>
    [Fact]
    public void Vectorize_EmptyString_ReturnsAllZeroVector()
    {
        var result = _sut.Vectorize(string.Empty);

        Assert.Equal(ExpectedVectorLength, result.Length);
        Assert.All(result, v => Assert.Equal(0f, v));
    }

    /// <summary>
    /// Whitespace-only input must be treated the same as empty.
    /// </summary>
    [Fact]
    public void Vectorize_WhitespaceOnly_ReturnsAllZeroVector()
    {
        var result = _sut.Vectorize("   \t\n  ");

        Assert.Equal(ExpectedVectorLength, result.Length);
        Assert.All(result, v => Assert.Equal(0f, v));
    }

    /// <summary>
    /// A normal job-description text should produce a non-zero vector
    /// of the expected length (5000).
    /// </summary>
    [Fact]
    public void Vectorize_ValidText_ReturnsVectorOfExpectedLength()
    {
        var result = _sut.Vectorize(
            "python developer with django rest api experience five years backend");

        Assert.Equal(ExpectedVectorLength, result.Length);
        // At least one element should be non-zero
        Assert.Contains(result, v => v > 0f);
    }

    /// <summary>
    /// Two semantically similar texts (same domain, overlapping vocabulary)
    /// should produce vectors with a high cosine similarity (≥ 0.7).
    /// </summary>
    [Fact]
    public void Vectorize_SimilarTexts_ProducesHighCosineSimilarity()
    {
        var vecA = _sut.Vectorize(
            "python developer django rest api backend experience");
        var vecB = _sut.Vectorize(
            "python engineer flask api backend web development");

        var similarity = _sut.CosineSimilarity(vecA, vecB);

        Assert.True(similarity >= SimilarThreshold,
            $"Expected cosine similarity ≥ {SimilarThreshold} (TF-IDF domain-similar texts) for similar texts, got {similarity:F4}. "
            + "Note: TF-IDF scores vocabulary overlap, not semantics. 0.35+ is healthy for same-domain texts.");
    }

    /// <summary>
    /// Two completely unrelated texts (tech vs. cooking) should produce
    /// vectors with a low cosine similarity (≤ 0.2).
    /// </summary>
    [Fact]
    public void Vectorize_UnrelatedTexts_ProducesLowCosineSimilarity()
    {
        var vecTech     = _sut.Vectorize(
            "python developer django rest api microservices kubernetes docker");
        var vecUnrelated = _sut.Vectorize(
            "chef cook restaurant kitchen culinary arts food preparation");

        var similarity = _sut.CosineSimilarity(vecTech, vecUnrelated);

        Assert.True(similarity <= UnrelatedThreshold,
            $"Expected cosine similarity ≤ {UnrelatedThreshold} for unrelated texts, got {similarity:F4}");
    }

    // ── CosineSimilarity() ───────────────────────────────────────────────────────

    /// <summary>
    /// Cosine similarity of a vector with itself must be exactly 1.0,
    /// because both vectors are L2-normalised by the ONNX model.
    /// </summary>
    [Fact]
    public void CosineSimilarity_IdenticalVectors_ReturnsOne()
    {
        var vec = _sut.Vectorize(
            "senior net engineer aspnet core microservices sql server azure");

        var result = _sut.CosineSimilarity(vec, vec);

        Assert.Equal(1.0, result, precision: 4);
    }

    /// <summary>
    /// When both input vectors are all-zero (e.g. completely out-of-vocabulary text),
    /// CosineSimilarity must return 0.0 and must NOT return NaN.
    /// </summary>
    [Fact]
    public void CosineSimilarity_BothZeroVectors_ReturnsZeroNotNaN()
    {
        var zero = new float[ExpectedVectorLength]; // all zeros

        var result = _sut.CosineSimilarity(zero, zero);

        Assert.False(double.IsNaN(result), "CosineSimilarity returned NaN for zero vectors.");
        Assert.Equal(0.0, result, precision: 4);
    }

    /// <summary>
    /// CosineSimilarity result must always be in the [0, 1] range.
    /// This guards against floating-point drift beyond valid bounds.
    /// </summary>
    [Fact]
    public void CosineSimilarity_ResultAlwaysClamped_BetweenZeroAndOne()
    {
        var vecA = _sut.Vectorize("software engineer machine learning python");
        var vecB = _sut.Vectorize("data scientist tensorflow pytorch nlp");

        var result = _sut.CosineSimilarity(vecA, vecB);

        Assert.True(result >= 0.0 && result <= 1.0,
            $"CosineSimilarity returned {result:F6} which is outside [0, 1].");
    }
}
